@SerwisSystem_Api_HostAddress = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjE2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ik1pa2UxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiV29ya2VyIiwiZXhwIjoxNzg5MDUzNjY2fQ.fE-9JA5aEPF9lQfy8EZ5HaW5sHk4ACK6J2wCnzHFT0c

###=====================================List of Repair requests=====================================

### List of all repairs
GET {{SerwisSystem_Api_HostAddress}}/api/repairs
Accept: application/json
Authorization: Bearer {{token}}


### Append new repair
POST {{SerwisSystem_Api_HostAddress}}/api/repairs
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "serialNumber": 2,
    "product": "iPhone 15",
    "description": "Broken screen",
    "name": "Jan",
    "surname": "Kowalski",
    "phoneNumber": "123456789",
    "email": "jan@example.com",
    "address": "Example 1",
    "nip": "1234567890"
}


### assign the user to repair with id ...

POST {{SerwisSystem_Api_HostAddress}}/api/repairs/18/take
Accept: application/json
Authorization: Bearer {{token}}


### complete the repair with id ...
POST {{SerwisSystem_Api_HostAddress}}/api/repairs/18/complete
Accept: application/json
Authorization: Bearer {{token}}


### cancel the repair with id ...  for now users are able to discharge admins
POST {{SerwisSystem_Api_HostAddress}}/api/repairs/21/cancel
Accept: application/json
Authorization: Bearer {{token}}


### return the repair with id ... for now users are able to discharge admins
POST {{SSerwisSystem_Api_HostAddress}}/api/repairs/22/return
Accept: application/json
Authorization: Bearer {{token}}


### Update repair with id ...
PUT {{SerwisSystem_Api_HostAddress}}/api/repairs/17
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "serialNumber": 23456,
    "status": 0,
    "product": "iPhone 25",
    "description": "Screen completely shattered",
    "name": "Jan",
    "surname": "Kowalski",
    "phoneNumber": "123456789",
    "email": "jan@example.com",
    "address": "Example 2",
    "nip": "1234567890"
}

### Delete repair with id ...
DELETE {{SerwisSystem_Api_HostAddress}}/api/repairs/20
Accept: application/json
Authorization: Bearer {{token}}


###=====================================List of User requests=====================================

### List of all users
GET {{SerwisSystem_Api_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### Selected user
GET {{SerwisSystem_Api_HostAddress}}/api/users/17
Accept: application/json
Authorization: Bearer {{token}}

### Logged user
GET {{SerwisSystem_Api_HostAddress}}/api/users/logged
Accept: application/json
Authorization: Bearer {{token}}

### Update user
PUT {{SerwisSystem_Api_HostAddress}}/api/users/13
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Username": "jonh76",
    "email": "jonh67@example.com"
}

### Delete user - here for now
DELETE {{SerwisSystem_Api_HostAddress}}/api/users/9
Accept: application/json
Authorization: Bearer {{token}}


### Edit user permissions 
# ===========================
# All of the permissions:
#         "ReadRepairs",
#         "TakeRepairs",
#         "EditRepairs",
#         "DeleteRepairs",
#         "ReadUsers",
#         "EditUsers",
#         "DeleteUsers",
#         "GrantUsers",
#         "DischargeUsers"
# ===========================
PUT {{SerwisSystem_Api_HostAddress}}/api/users/grant/17
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "permissionsGranted": [
       "GrantUsers",
        "ReadRepairs",
        "TakeRepairs",
        "EditRepairs",
        "DeleteRepairs",
        "ReadUsers",
        "EditUsers",
        "DeleteUsers",
        "DischargeUsers"
    ],
    "permissionsRevoked": [

    ]
}
###

###=====================================List of Authorization requests=====================================

### register user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Mike2",
    "email": "Mike2@gmail.com",
    "password": "password123"
}

### login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "UsernameOrEmail": "Mike1",
    "password": "password123"
}

### create admin
POST http://localhost:5000/api/auth/createAdmin
Content-Type: application/json

{
    "username": "John4",
    "email": "john4@gmail.com",
    "password": "password123"
}